// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/busyrat/iWork/imooc_gp/node_modules/react');
var { Component } = React;
var ReactNative = require('/Users/busyrat/iWork/imooc_gp/node_modules/react-native');
var { AppRegistry } = ReactNative;
var entryPoint = require('/Users/busyrat/iWork/imooc_gp/index.ios.js');
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('imooc_gp', appParameters);
});